### ISSUE TITLE
retic blows up when importing a class to a different file.

### ISSUE THREAD

**Issue by migeed-z** [mvitousek/reticulated#11]
The following code does not work:
class A:

    def __init__(self):
        pass

    def m(self) -> A:
        return A()

This method is in a different file:

<code>
 def m2(x: A):
    return x
</code>

When the method and the class are in the same file the code works.

Error message:

<code>
Traceback (most recent call last):
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/bin/retic", line 9, in <module>
    load_entry_point('retic==0.1.0', 'console_scripts', 'retic')()
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/retic.py", line 145, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/retic.py", line 45, in reticulate
    typed_ast, _ = type_system.typecheck_module(py_ast, module_name)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/static.py", line 21, in typecheck_module
    return self.typecheck(mod, ext, ext, Misc(filename=filename, depth=depth, static=self))
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/static.py", line 56, in typecheck
    annotated = typefinder.Typefinder().preorder(n, False, alias_scope, misc)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/typefinder.py", line 49, in preorder
    return super().preorder(n, vty, aliases, misc)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/vis.py", line 36, in preorder
    return self.dispatch(tree, *args)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/vis.py", line 28, in dispatch
    ret = meth(node, *args)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 37, in visitModule
    return self.dispatch_statements(n.body, *args)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 34, in dispatch_statements
    return self.reduce_stmt(ns, *args)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 14, in reduce_stmt
    return reduce(self.combine_stmt, [self.dispatch(n, *args) for n in ns], 
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 14, in <listcomp>
    return reduce(self.combine_stmt, [self.dispatch(n, *args) for n in ns], 
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/vis.py", line 28, in dispatch
    ret = meth(node, *args)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/typefinder.py", line 130, in visitFunctionDef
    argannot = typeparse(arg.annotation, aliases)
  File "/Users/zeinamigeed/Documents/reticulated/retic-env/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/typefinder.py", line 25, in typeparse
    exec(code, globs, locs)
  File "<string>", line 3, in <module>
NameError: name 'A' is not defined
</code>

I'm running on python3.3 on a virtual environment in OS X 10.10.5, and I just added the attached two files to the rest of the tutorials that come in the repo. 

[files.zip](https://github.com/mvitousek/reticulated/files/86179/files.zip)

**Comment by mvitousek** [comment]
I think you're getting this error because you're trying to import docs.tutorial5 rather than just tutorial5. Try removing type annotations from these files and running them just with Python, I think you'll get a Python error (if you don't, then let me know). Try replacing the import in tutorial7 with `from tutorial5 import A`; if there's still a problem let me know and otherwise I'll close this in a few days.

I certainly can do better in terms of error messages though.

**Comment by migeed-z** [comment]
Unfortunately I am still getting the same error. I'm running on python3.3, could that be causing any issue?

**Comment by mvitousek** [comment]
I don't think that could be the problem, I've tested it on 3.3 and it works fine for me. Could you attach your updated files? I'll take another look.

**Comment by migeed-z** [comment]
Hello Michael, very sorry for the delay. Attached are the new files. Thank you!
[files.zip](https://github.com/mvitousek/reticulated/files/96205/files.zip)

**Comment by mvitousek** [comment]
I've managed to reproduce this error on Mac -- unfortunately, seems like there is a platform-specific problem here, as the problem doesn't occur on any of the Linux installs I've tested against. I'll push a fix ASAP although my access to Macs is limited. Thanks for pointing this out.

**Comment by mvitousek** [comment]
I've pushed a fix -- please let me know if there's any problems with it! Sorry for taking so long.

**Comment by migeed-z** [comment]
Hello Michael, unfortunately this is still not working for me. 

I made new examples and attached them below. 

This is the error message: 

`Traceback (most recent call last):
  File "/Users/zeinamigeed/Documents/reticulated_python/bin/retic", line 9, in <module>
    load_entry_point('retic==0.1.0', 'console_scripts', 'retic')()
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/retic.py", line 148, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/retic.py", line 48, in reticulate
    typed_ast, _ = type_system.typecheck_module(py_ast, module_name)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/static.py", line 21, in typecheck_module
    return self.typecheck(mod, ext, ext, Misc(filename=filename, depth=depth, static=self))
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/static.py", line 56, in typecheck
    annotated = typefinder.Typefinder().preorder(n, False, alias_scope, misc)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/typefinder.py", line 49, in preorder
    return super().preorder(n, vty, aliases, misc)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/vis.py", line 36, in preorder
    return self.dispatch(tree, *args)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/vis.py", line 28, in dispatch
    ret = meth(node, *args)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 37, in visitModule
    return self.dispatch_statements(n.body, *args)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 34, in dispatch_statements
    return self.reduce_stmt(ns, *args)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 14, in reduce_stmt
    return reduce(self.combine_stmt, [self.dispatch(n, *args) for n in ns], 
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/visitors.py", line 14, in <listcomp>
    return reduce(self.combine_stmt, [self.dispatch(n, *args) for n in ns], 
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/vis.py", line 28, in dispatch
    ret = meth(node, *args)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/typefinder.py", line 114, in visitFunctionDef
    ret = typeparse(n.returns, aliases)
  File "/Users/zeinamigeed/Documents/reticulated_python/lib/python3.3/site-packages/retic-0.1.0-py3.3.egg/retic/typefinder.py", line 25, in typeparse
    exec(code, globs, locs)
  File "<string>", line 3, in <module>
NameError: name 'B' is not defined
`




[retic_files.zip](https://github.com/mvitousek/reticulated/files/110587/retic_files.zip)
